# Generated by Django 2.0.4 on 2018-05-02 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notifications_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notifications',
            options={'ordering': ['-created_at']},
        ),
    ]
